---
title: "About"
description-meta: "About Emre Amasyalı, postdoctoral researcher studying nationalism, ethnic conflict, and imperialism."
title-block-banner: false
page-layout: full
toc: false
---

<div class="content-box">

I am a social sciences researcher specializing in the analysis of the dynamics of nation-building and their long-term effects on ethnic group relations, conflict, and socio-political change. My work offers a comparative perspective on the consequences of Western (e.g., British, French) and non-Western (Ottoman Empire) models of nation- and empire-building. By integrating Geographic Information System (GIS) tools, quantitative methods, and archival research with traditional qualitative analysis, I employ innovative methodologies to advance historical and comparative studies. I hold a PhD from McGill University, where my research and teaching earned multiple awards for excellence, and a Master's degree from the University of Oxford. Currently, I serve as a Juan de la Cierva Postdoctoral Fellow at the Institut Barcelona d'Estudis Internacionals (IBEI) and am a Postdoctoral Researcher for the ERC-funded ETHNICGOODS project. Currently, I am working on a series of collaborative research articles that explore topics such as cultural elimination, language grievances and ethnic conflict, and the pitfalls of anachronism in social science.

</div>
