---
title: "Publications"
description-meta: "Academic publications by Emre Amasyalı"
title-block-banner: false
page-layout: full
toc: false
---

<div class="content-box">

**Amasyalı, E.** & Tarasov, A. (2025). [Nation-building in the wake of empire: Identifying patterns of minority policies in the aftermath of Soviet collapse](https://doi.org/10.1111/nana.13162). *Nations and Nationalism*, 1–16.

van den Berg, A. & **Amasyalı, E.** (2025). What Do We Need "Agency" for? A Critical Analysis of Reasons for the Use of "Agency" in Sociology. *Current Perspective in Social Theory*, 41, 15–41.

**Amasyalı, E.** & van den Berg, A. (2025). What Do We Use "Agency" for? A Critical Empirical Examination of Its Uses in the Sociological Literature. *Current Perspective in Social Theory*, 41, 43–76.

van den Berg, A. & **Amasyalı, E.** (2025). Why Do We Need to Discuss Agency? *Current Perspective in Social Theory*, 41, 117–125.

**Amasyalı, E.** & Hall, J. A. (2022). [War as the catalyst of nationalism, or, the demise of the Habsburg, Romanov and Ottoman empires](https://journals.sagepub.com/doi/10.1177/07255136221141514). *Thesis Eleven*, 173(1), 3–23.

**Amasyalı, E.** (2022). [Indigenous responses to Protestant missionaries: Educational competition and economic development in Ottoman Turkey](https://www.cambridge.org/core/journals/european-journal-of-sociology-archives-europeennes-de-sociologie/article/abs/indigenous-responses-to-protestant-missionaries-educational-competition-and-economic-development-in-ottoman-turkey/863D9E23A1BF978BB1C29FC2495385D3). *European Journal of Sociology/Archives Européennes de Sociologie*, 63(1), 39–86.

**Amasyalı, E.** (2022). [Protestant missionary education and the diffusion of women's education in Ottoman Turkey: A historical GIS analysis](https://www.cambridge.org/core/journals/social-science-history/article/abs/protestant-missionary-education-and-the-diffusion-of-womens-education-in-ottoman-turkey-a-historical-gis-analysis/C9658330B69E4F064A74D9FC1B529D41). *Social Science History*, 46(1), 173–222.

Lange, M., **Amasyalı, E.** & Jeong, T. (2021). [Communalizing colonial policies and postcolonial ethnic warfare: A multimethod analysis of the British empire](https://www.cambridge.org/core/journals/european-journal-of-sociology-archives-europeennes-de-sociologie/article/communalizing-colonial-policies-and-postcolonial-ethnic-warfare-a-multimethod-analysis-of-the-british-empire-erratum/6D1FA4AFB351A1E1F88AF14F3CD2F312). *European Journal of Sociology/Archives Européennes de Sociologie*, 62(3), 337–379.

Lange, M., Jeong, T. & **Amasyalı, E.** (2021). [The colonial origins of ethnic warfare: Re-examining the impact of communalizing colonial policies in the British and French empires](https://journals.sagepub.com/doi/full/10.1177/00207152211023793). *International Journal of Comparative Sociology*, 62(2), 141–165.

**Amasyalı, E.** (2020). [Missionary influence and nationalist reactions: The case of Armenian Ottomans](https://www.cambridge.org/core/journals/nationalities-papers/article/abs/missionary-influence-and-nationalist-reactions-the-case-of-armenian-ottomans/126F4C5D5EBC93B07FFB5BD92EB83B24). *Nationalities Papers*, 49(3), 523–541.

</div>